"$schema" = 'https://starship.rs/config-schema.json'

format = '$all'

[username]
disabled = false
show_always = true
style_user = 'bold yellow'
style_root = 'bold red'
format = '[$user]($style) '

[hostname]
disabled = false
ssh_only = false
ssh_symbol = 'î¬ '
trim_at = '.'
format = '@ [$hostname](bold green) '

[localip]
disabled = true

[character]
disabled = false
success_symbol = '[>](bold green)'
error_symbol = '[x](bold red)'

[directory]
read_only = ' ó°Œ¾'
truncation_length = 10
truncation_symbol = 'â€¦/'

[cmd_duration]
disabled = false
show_milliseconds = false
style = 'bold italic red'

[time]
disabled = false
time_format = '%T' # Hour:Minute:Second Format
style = 'bg:#1d2230'
format = '[ ïº $time ]($style)'

[directory.substitutions]
'Documents' = 'Docs'
'Downloads' = 'Downloads'
'Music' = 'Music'
'Pictures' = 'Pics'

[memory_usage]
symbol = 'ó°› '

[git_branch]
disabled = false
symbol = 'ï˜ '

[git_commit]
tag_symbol = ' ğŸ· '

[git_status]
ahead = '>'
behind = '<'
diverged = '<>'
renamed = 'r'
deleted = 'x'

[git_state]
style =	'bold red'
format = '[$state( $progress_current/$progress_total) ]($style)'
rebase = 'rebase'
merge = 'merge'	
revert = 'revert'	
cherry_pick = 'cherry'
bisect = 'bisect'	
am = 'am'	
am_or_rebase = 'am/rebase'

### Symbols for various languages/frameworks/runtimes etc. ###
[aws]
symbol = 'îŒ½  '

[buf]
symbol = 'ï’ '

[c]
symbol = 'î˜ '

[conda]
symbol = 'ï„Œ '

[crystal]
symbol = 'î˜¯ '

[dart]
symbol = 'î˜ '

[docker_context]
symbol = 'ïŒˆ '

[elixir]
symbol = 'î˜­ '

[elm]
symbol = 'î˜¬ '

[fennel]
symbol = 'îš¯ '

[fossil_branch]
symbol = 'ï˜ '

[golang]
symbol = 'î˜§ '

[guix_shell]
symbol = 'ïŒ¥ '

[haskell]
symbol = 'î· '

[haxe]
symbol = 'î™¦ '

[hg_branch]
symbol = 'ï˜ '

[java]
symbol = 'î‰– '

[julia]
symbol = 'î˜¤ '

[kotlin]
symbol = 'î˜´ '

[lua]
symbol = 'î˜  '

[meson]
symbol = 'ó°”· '

[nim]
symbol = 'ó°†¥ '

[nix_shell]
symbol = 'ïŒ“ '

[nodejs]
symbol = 'îœ˜ '

[ocaml]
symbol = 'î™º '

[os.symbols]
Alpaquita = 'îª¢ '
Alpine = 'ïŒ€ '
AlmaLinux = 'ïŒ '
Amazon = 'ï‰° '
Android = 'ï…» '
Arch = 'ïŒƒ '
Artix = 'ïŒŸ '
CentOS = 'ïŒ„ '
Debian = 'ïŒ† '
DragonFly = 'îŠ '
Emscripten = 'ïˆ… '
EndeavourOS = 'ï†— '
Fedora = 'ïŒŠ '
FreeBSD = 'ïŒŒ '
Garuda = 'ó°›“ '
Gentoo = 'ïŒ '
HardenedBSD = 'ó°Œ '
Illumos = 'ó°ˆ¸ '
Kali = 'ïŒ§ '
Linux = 'ïŒš '
Mabox = 'î¬© '
Macos = 'ïŒ‚ '
Manjaro = 'ïŒ’ '
Mariner = 'ï‡ '
MidnightBSD = 'ï†† '
Mint = 'ïŒ '
NetBSD = 'ï€¤ '
NixOS = 'ïŒ“ '
OpenBSD = 'ó°ˆº '
openSUSE = 'ïŒ” '
OracleLinux = 'ó°Œ· '
Pop = 'ïŒª '
Raspbian = 'ïŒ• '
Redhat = 'ïŒ– '
RedHatEnterprise = 'ïŒ– '
RockyLinux = 'ïŒ« '
Redox = 'ó°€˜ '
Solus = 'ó° ³ '
SUSE = 'ïŒ” '
Ubuntu = 'ïŒ› '
Unknown = 'ïˆ­ '
Void = 'ïŒ® '
Windows = 'ó°² '

[package]
symbol = 'ó°— '

[perl]
symbol = 'î™¾ '

[php]
symbol = 'î˜ˆ '

[pijul_channel]
symbol = 'ï˜ '

[python]
symbol = 'îˆµ '

[rlang]
symbol = 'ó°Ÿ” '

[ruby]
symbol = 'î‘ '

[rust]
symbol = 'î¨ '

[scala]
symbol = 'îœ· '

[swift]
symbol = 'î• '

[zig]
symbol = 'îš© '
